//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P29.Course.SOA.UnitTestProject.MyWCFTest {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyWCFTest.ICustomService")]
    public interface ICustomService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomService/DoWork", ReplyAction="http://tempuri.org/ICustomService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomService/DoWork", ReplyAction="http://tempuri.org/ICustomService/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomService/Get", ReplyAction="http://tempuri.org/ICustomService/GetResponse")]
        int Get();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomService/Get", ReplyAction="http://tempuri.org/ICustomService/GetResponse")]
        System.Threading.Tasks.Task<int> GetAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomServiceChannel : P29.Course.SOA.UnitTestProject.MyWCFTest.ICustomService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomServiceClient : System.ServiceModel.ClientBase<P29.Course.SOA.UnitTestProject.MyWCFTest.ICustomService>, P29.Course.SOA.UnitTestProject.MyWCFTest.ICustomService {
        
        public CustomServiceClient() {
        }
        
        public CustomServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public int Get() {
            return base.Channel.Get();
        }
        
        public System.Threading.Tasks.Task<int> GetAsync() {
            return base.Channel.GetAsync();
        }
    }
}
