//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P33.Course.DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysUser
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public byte Status { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public Nullable<long> QQ { get; set; }
        public string WeChat { get; set; }
        public Nullable<byte> Sex { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int CreateId { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
        public Nullable<int> LastModifyId { get; set; }
    }
}
