//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P37.Course.Web.SearchEnginesForm.WeatherService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Weather", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Weather : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime ShowDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IconField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TemperatureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WindSpeedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime ShowDate {
            get {
                return this.ShowDateField;
            }
            set {
                if ((this.ShowDateField.Equals(value) != true)) {
                    this.ShowDateField = value;
                    this.RaisePropertyChanged("ShowDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Icon {
            get {
                return this.IconField;
            }
            set {
                if ((object.ReferenceEquals(this.IconField, value) != true)) {
                    this.IconField = value;
                    this.RaisePropertyChanged("Icon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Temperature {
            get {
                return this.TemperatureField;
            }
            set {
                if ((object.ReferenceEquals(this.TemperatureField, value) != true)) {
                    this.TemperatureField = value;
                    this.RaisePropertyChanged("Temperature");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string WindSpeed {
            get {
                return this.WindSpeedField;
            }
            set {
                if ((object.ReferenceEquals(this.WindSpeedField, value) != true)) {
                    this.WindSpeedField = value;
                    this.RaisePropertyChanged("WindSpeed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Remark {
            get {
                return this.RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarkField, value) != true)) {
                    this.RemarkField = value;
                    this.RaisePropertyChanged("Remark");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WeatherService.ForecastServiceSoap")]
    public interface ForecastServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        P37.Course.Web.SearchEnginesForm.WeatherService.HelloWorldResponse HelloWorld(P37.Course.Web.SearchEnginesForm.WeatherService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<P37.Course.Web.SearchEnginesForm.WeatherService.HelloWorldResponse> HelloWorldAsync(P37.Course.Web.SearchEnginesForm.WeatherService.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name GetWeathersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWeathers", ReplyAction="*")]
        P37.Course.Web.SearchEnginesForm.WeatherService.GetWeathersResponse GetWeathers(P37.Course.Web.SearchEnginesForm.WeatherService.GetWeathersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWeathers", ReplyAction="*")]
        System.Threading.Tasks.Task<P37.Course.Web.SearchEnginesForm.WeatherService.GetWeathersResponse> GetWeathersAsync(P37.Course.Web.SearchEnginesForm.WeatherService.GetWeathersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public P37.Course.Web.SearchEnginesForm.WeatherService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(P37.Course.Web.SearchEnginesForm.WeatherService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public P37.Course.Web.SearchEnginesForm.WeatherService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(P37.Course.Web.SearchEnginesForm.WeatherService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWeathersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWeathers", Namespace="http://tempuri.org/", Order=0)]
        public P37.Course.Web.SearchEnginesForm.WeatherService.GetWeathersRequestBody Body;
        
        public GetWeathersRequest() {
        }
        
        public GetWeathersRequest(P37.Course.Web.SearchEnginesForm.WeatherService.GetWeathersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetWeathersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CityCode;
        
        public GetWeathersRequestBody() {
        }
        
        public GetWeathersRequestBody(int CityCode) {
            this.CityCode = CityCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWeathersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWeathersResponse", Namespace="http://tempuri.org/", Order=0)]
        public P37.Course.Web.SearchEnginesForm.WeatherService.GetWeathersResponseBody Body;
        
        public GetWeathersResponse() {
        }
        
        public GetWeathersResponse(P37.Course.Web.SearchEnginesForm.WeatherService.GetWeathersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetWeathersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public P37.Course.Web.SearchEnginesForm.WeatherService.Weather[] GetWeathersResult;
        
        public GetWeathersResponseBody() {
        }
        
        public GetWeathersResponseBody(P37.Course.Web.SearchEnginesForm.WeatherService.Weather[] GetWeathersResult) {
            this.GetWeathersResult = GetWeathersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ForecastServiceSoapChannel : P37.Course.Web.SearchEnginesForm.WeatherService.ForecastServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ForecastServiceSoapClient : System.ServiceModel.ClientBase<P37.Course.Web.SearchEnginesForm.WeatherService.ForecastServiceSoap>, P37.Course.Web.SearchEnginesForm.WeatherService.ForecastServiceSoap {
        
        public ForecastServiceSoapClient() {
        }
        
        public ForecastServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ForecastServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ForecastServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ForecastServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        P37.Course.Web.SearchEnginesForm.WeatherService.HelloWorldResponse P37.Course.Web.SearchEnginesForm.WeatherService.ForecastServiceSoap.HelloWorld(P37.Course.Web.SearchEnginesForm.WeatherService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            P37.Course.Web.SearchEnginesForm.WeatherService.HelloWorldRequest inValue = new P37.Course.Web.SearchEnginesForm.WeatherService.HelloWorldRequest();
            inValue.Body = new P37.Course.Web.SearchEnginesForm.WeatherService.HelloWorldRequestBody();
            P37.Course.Web.SearchEnginesForm.WeatherService.HelloWorldResponse retVal = ((P37.Course.Web.SearchEnginesForm.WeatherService.ForecastServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<P37.Course.Web.SearchEnginesForm.WeatherService.HelloWorldResponse> P37.Course.Web.SearchEnginesForm.WeatherService.ForecastServiceSoap.HelloWorldAsync(P37.Course.Web.SearchEnginesForm.WeatherService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<P37.Course.Web.SearchEnginesForm.WeatherService.HelloWorldResponse> HelloWorldAsync() {
            P37.Course.Web.SearchEnginesForm.WeatherService.HelloWorldRequest inValue = new P37.Course.Web.SearchEnginesForm.WeatherService.HelloWorldRequest();
            inValue.Body = new P37.Course.Web.SearchEnginesForm.WeatherService.HelloWorldRequestBody();
            return ((P37.Course.Web.SearchEnginesForm.WeatherService.ForecastServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        P37.Course.Web.SearchEnginesForm.WeatherService.GetWeathersResponse P37.Course.Web.SearchEnginesForm.WeatherService.ForecastServiceSoap.GetWeathers(P37.Course.Web.SearchEnginesForm.WeatherService.GetWeathersRequest request) {
            return base.Channel.GetWeathers(request);
        }
        
        public P37.Course.Web.SearchEnginesForm.WeatherService.Weather[] GetWeathers(int CityCode) {
            P37.Course.Web.SearchEnginesForm.WeatherService.GetWeathersRequest inValue = new P37.Course.Web.SearchEnginesForm.WeatherService.GetWeathersRequest();
            inValue.Body = new P37.Course.Web.SearchEnginesForm.WeatherService.GetWeathersRequestBody();
            inValue.Body.CityCode = CityCode;
            P37.Course.Web.SearchEnginesForm.WeatherService.GetWeathersResponse retVal = ((P37.Course.Web.SearchEnginesForm.WeatherService.ForecastServiceSoap)(this)).GetWeathers(inValue);
            return retVal.Body.GetWeathersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<P37.Course.Web.SearchEnginesForm.WeatherService.GetWeathersResponse> P37.Course.Web.SearchEnginesForm.WeatherService.ForecastServiceSoap.GetWeathersAsync(P37.Course.Web.SearchEnginesForm.WeatherService.GetWeathersRequest request) {
            return base.Channel.GetWeathersAsync(request);
        }
        
        public System.Threading.Tasks.Task<P37.Course.Web.SearchEnginesForm.WeatherService.GetWeathersResponse> GetWeathersAsync(int CityCode) {
            P37.Course.Web.SearchEnginesForm.WeatherService.GetWeathersRequest inValue = new P37.Course.Web.SearchEnginesForm.WeatherService.GetWeathersRequest();
            inValue.Body = new P37.Course.Web.SearchEnginesForm.WeatherService.GetWeathersRequestBody();
            inValue.Body.CityCode = CityCode;
            return ((P37.Course.Web.SearchEnginesForm.WeatherService.ForecastServiceSoap)(this)).GetWeathersAsync(inValue);
        }
    }
}
