//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P29.Course.SOA.UnitTestProject.MyWebServiceTest {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UserInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private int AgeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyWebServiceTest.MyWebServiceSoap")]
    public interface MyWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        P29.Course.SOA.UnitTestProject.MyWebServiceTest.HelloWorldResponse HelloWorld(P29.Course.SOA.UnitTestProject.MyWebServiceTest.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<P29.Course.SOA.UnitTestProject.MyWebServiceTest.HelloWorldResponse> HelloWorldAsync(P29.Course.SOA.UnitTestProject.MyWebServiceTest.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name name_password from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorldWithAuth", ReplyAction="*")]
        P29.Course.SOA.UnitTestProject.MyWebServiceTest.HelloWorldWithAuthResponse HelloWorldWithAuth(P29.Course.SOA.UnitTestProject.MyWebServiceTest.HelloWorldWithAuthRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorldWithAuth", ReplyAction="*")]
        System.Threading.Tasks.Task<P29.Course.SOA.UnitTestProject.MyWebServiceTest.HelloWorldWithAuthResponse> HelloWorldWithAuthAsync(P29.Course.SOA.UnitTestProject.MyWebServiceTest.HelloWorldWithAuthRequest request);
        
        // CODEGEN: Generating message contract since element name GetNameByIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNameById", ReplyAction="*")]
        P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetNameByIdResponse GetNameById(P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetNameByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNameById", ReplyAction="*")]
        System.Threading.Tasks.Task<P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetNameByIdResponse> GetNameByIdAsync(P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetNameByIdRequest request);
        
        // CODEGEN: Generating message contract since element name GetUserObjByIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserObjById", ReplyAction="*")]
        P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetUserObjByIdResponse GetUserObjById(P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetUserObjByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserObjById", ReplyAction="*")]
        System.Threading.Tasks.Task<P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetUserObjByIdResponse> GetUserObjByIdAsync(P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetUserObjByIdRequest request);
        
        // CODEGEN: Generating message contract since element name GetuserListResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetuserList", ReplyAction="*")]
        P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetuserListResponse GetuserList(P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetuserListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetuserList", ReplyAction="*")]
        System.Threading.Tasks.Task<P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetuserListResponse> GetuserListAsync(P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetuserListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Plus", ReplyAction="*")]
        int Plus(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Plus", ReplyAction="*")]
        System.Threading.Tasks.Task<int> PlusAsync(int x, int y);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetJsonInfo", ReplyAction="*")]
        P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetJsonInfoResponse GetJsonInfo(P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetJsonInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetJsonInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetJsonInfoResponse> GetJsonInfoAsync(P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetJsonInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public P29.Course.SOA.UnitTestProject.MyWebServiceTest.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(P29.Course.SOA.UnitTestProject.MyWebServiceTest.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public P29.Course.SOA.UnitTestProject.MyWebServiceTest.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(P29.Course.SOA.UnitTestProject.MyWebServiceTest.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldWithAuthRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldWithAuth", Namespace="http://tempuri.org/", Order=0)]
        public P29.Course.SOA.UnitTestProject.MyWebServiceTest.HelloWorldWithAuthRequestBody Body;
        
        public HelloWorldWithAuthRequest() {
        }
        
        public HelloWorldWithAuthRequest(P29.Course.SOA.UnitTestProject.MyWebServiceTest.HelloWorldWithAuthRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldWithAuthRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name_password;
        
        public HelloWorldWithAuthRequestBody() {
        }
        
        public HelloWorldWithAuthRequestBody(string name_password) {
            this.name_password = name_password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldWithAuthResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldWithAuthResponse", Namespace="http://tempuri.org/", Order=0)]
        public P29.Course.SOA.UnitTestProject.MyWebServiceTest.HelloWorldWithAuthResponseBody Body;
        
        public HelloWorldWithAuthResponse() {
        }
        
        public HelloWorldWithAuthResponse(P29.Course.SOA.UnitTestProject.MyWebServiceTest.HelloWorldWithAuthResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldWithAuthResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldWithAuthResult;
        
        public HelloWorldWithAuthResponseBody() {
        }
        
        public HelloWorldWithAuthResponseBody(string HelloWorldWithAuthResult) {
            this.HelloWorldWithAuthResult = HelloWorldWithAuthResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNameByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNameById", Namespace="http://tempuri.org/", Order=0)]
        public P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetNameByIdRequestBody Body;
        
        public GetNameByIdRequest() {
        }
        
        public GetNameByIdRequest(P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetNameByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNameByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetNameByIdRequestBody() {
        }
        
        public GetNameByIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNameByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNameByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetNameByIdResponseBody Body;
        
        public GetNameByIdResponse() {
        }
        
        public GetNameByIdResponse(P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetNameByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNameByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetNameByIdResult;
        
        public GetNameByIdResponseBody() {
        }
        
        public GetNameByIdResponseBody(string GetNameByIdResult) {
            this.GetNameByIdResult = GetNameByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserObjByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserObjById", Namespace="http://tempuri.org/", Order=0)]
        public P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetUserObjByIdRequestBody Body;
        
        public GetUserObjByIdRequest() {
        }
        
        public GetUserObjByIdRequest(P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetUserObjByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserObjByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetUserObjByIdRequestBody() {
        }
        
        public GetUserObjByIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserObjByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserObjByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetUserObjByIdResponseBody Body;
        
        public GetUserObjByIdResponse() {
        }
        
        public GetUserObjByIdResponse(P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetUserObjByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserObjByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public P29.Course.SOA.UnitTestProject.MyWebServiceTest.UserInfo GetUserObjByIdResult;
        
        public GetUserObjByIdResponseBody() {
        }
        
        public GetUserObjByIdResponseBody(P29.Course.SOA.UnitTestProject.MyWebServiceTest.UserInfo GetUserObjByIdResult) {
            this.GetUserObjByIdResult = GetUserObjByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetuserListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetuserList", Namespace="http://tempuri.org/", Order=0)]
        public P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetuserListRequestBody Body;
        
        public GetuserListRequest() {
        }
        
        public GetuserListRequest(P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetuserListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetuserListRequestBody {
        
        public GetuserListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetuserListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetuserListResponse", Namespace="http://tempuri.org/", Order=0)]
        public P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetuserListResponseBody Body;
        
        public GetuserListResponse() {
        }
        
        public GetuserListResponse(P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetuserListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetuserListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<P29.Course.SOA.UnitTestProject.MyWebServiceTest.UserInfo> GetuserListResult;
        
        public GetuserListResponseBody() {
        }
        
        public GetuserListResponseBody(System.Collections.Generic.List<P29.Course.SOA.UnitTestProject.MyWebServiceTest.UserInfo> GetuserListResult) {
            this.GetuserListResult = GetuserListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetJsonInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetJsonInfo", Namespace="http://tempuri.org/", Order=0)]
        public P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetJsonInfoRequestBody Body;
        
        public GetJsonInfoRequest() {
        }
        
        public GetJsonInfoRequest(P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetJsonInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetJsonInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int age;
        
        public GetJsonInfoRequestBody() {
        }
        
        public GetJsonInfoRequestBody(int id, string name, int age) {
            this.id = id;
            this.name = name;
            this.age = age;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetJsonInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetJsonInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetJsonInfoResponseBody Body;
        
        public GetJsonInfoResponse() {
        }
        
        public GetJsonInfoResponse(P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetJsonInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetJsonInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetJsonInfoResult;
        
        public GetJsonInfoResponseBody() {
        }
        
        public GetJsonInfoResponseBody(string GetJsonInfoResult) {
            this.GetJsonInfoResult = GetJsonInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MyWebServiceSoapChannel : P29.Course.SOA.UnitTestProject.MyWebServiceTest.MyWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyWebServiceSoapClient : System.ServiceModel.ClientBase<P29.Course.SOA.UnitTestProject.MyWebServiceTest.MyWebServiceSoap>, P29.Course.SOA.UnitTestProject.MyWebServiceTest.MyWebServiceSoap {
        
        public MyWebServiceSoapClient() {
        }
        
        public MyWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        P29.Course.SOA.UnitTestProject.MyWebServiceTest.HelloWorldResponse P29.Course.SOA.UnitTestProject.MyWebServiceTest.MyWebServiceSoap.HelloWorld(P29.Course.SOA.UnitTestProject.MyWebServiceTest.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            P29.Course.SOA.UnitTestProject.MyWebServiceTest.HelloWorldRequest inValue = new P29.Course.SOA.UnitTestProject.MyWebServiceTest.HelloWorldRequest();
            inValue.Body = new P29.Course.SOA.UnitTestProject.MyWebServiceTest.HelloWorldRequestBody();
            P29.Course.SOA.UnitTestProject.MyWebServiceTest.HelloWorldResponse retVal = ((P29.Course.SOA.UnitTestProject.MyWebServiceTest.MyWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<P29.Course.SOA.UnitTestProject.MyWebServiceTest.HelloWorldResponse> P29.Course.SOA.UnitTestProject.MyWebServiceTest.MyWebServiceSoap.HelloWorldAsync(P29.Course.SOA.UnitTestProject.MyWebServiceTest.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<P29.Course.SOA.UnitTestProject.MyWebServiceTest.HelloWorldResponse> HelloWorldAsync() {
            P29.Course.SOA.UnitTestProject.MyWebServiceTest.HelloWorldRequest inValue = new P29.Course.SOA.UnitTestProject.MyWebServiceTest.HelloWorldRequest();
            inValue.Body = new P29.Course.SOA.UnitTestProject.MyWebServiceTest.HelloWorldRequestBody();
            return ((P29.Course.SOA.UnitTestProject.MyWebServiceTest.MyWebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        P29.Course.SOA.UnitTestProject.MyWebServiceTest.HelloWorldWithAuthResponse P29.Course.SOA.UnitTestProject.MyWebServiceTest.MyWebServiceSoap.HelloWorldWithAuth(P29.Course.SOA.UnitTestProject.MyWebServiceTest.HelloWorldWithAuthRequest request) {
            return base.Channel.HelloWorldWithAuth(request);
        }
        
        public string HelloWorldWithAuth(string name_password) {
            P29.Course.SOA.UnitTestProject.MyWebServiceTest.HelloWorldWithAuthRequest inValue = new P29.Course.SOA.UnitTestProject.MyWebServiceTest.HelloWorldWithAuthRequest();
            inValue.Body = new P29.Course.SOA.UnitTestProject.MyWebServiceTest.HelloWorldWithAuthRequestBody();
            inValue.Body.name_password = name_password;
            P29.Course.SOA.UnitTestProject.MyWebServiceTest.HelloWorldWithAuthResponse retVal = ((P29.Course.SOA.UnitTestProject.MyWebServiceTest.MyWebServiceSoap)(this)).HelloWorldWithAuth(inValue);
            return retVal.Body.HelloWorldWithAuthResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<P29.Course.SOA.UnitTestProject.MyWebServiceTest.HelloWorldWithAuthResponse> P29.Course.SOA.UnitTestProject.MyWebServiceTest.MyWebServiceSoap.HelloWorldWithAuthAsync(P29.Course.SOA.UnitTestProject.MyWebServiceTest.HelloWorldWithAuthRequest request) {
            return base.Channel.HelloWorldWithAuthAsync(request);
        }
        
        public System.Threading.Tasks.Task<P29.Course.SOA.UnitTestProject.MyWebServiceTest.HelloWorldWithAuthResponse> HelloWorldWithAuthAsync(string name_password) {
            P29.Course.SOA.UnitTestProject.MyWebServiceTest.HelloWorldWithAuthRequest inValue = new P29.Course.SOA.UnitTestProject.MyWebServiceTest.HelloWorldWithAuthRequest();
            inValue.Body = new P29.Course.SOA.UnitTestProject.MyWebServiceTest.HelloWorldWithAuthRequestBody();
            inValue.Body.name_password = name_password;
            return ((P29.Course.SOA.UnitTestProject.MyWebServiceTest.MyWebServiceSoap)(this)).HelloWorldWithAuthAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetNameByIdResponse P29.Course.SOA.UnitTestProject.MyWebServiceTest.MyWebServiceSoap.GetNameById(P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetNameByIdRequest request) {
            return base.Channel.GetNameById(request);
        }
        
        public string GetNameById(int id) {
            P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetNameByIdRequest inValue = new P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetNameByIdRequest();
            inValue.Body = new P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetNameByIdRequestBody();
            inValue.Body.id = id;
            P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetNameByIdResponse retVal = ((P29.Course.SOA.UnitTestProject.MyWebServiceTest.MyWebServiceSoap)(this)).GetNameById(inValue);
            return retVal.Body.GetNameByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetNameByIdResponse> P29.Course.SOA.UnitTestProject.MyWebServiceTest.MyWebServiceSoap.GetNameByIdAsync(P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetNameByIdRequest request) {
            return base.Channel.GetNameByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetNameByIdResponse> GetNameByIdAsync(int id) {
            P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetNameByIdRequest inValue = new P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetNameByIdRequest();
            inValue.Body = new P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetNameByIdRequestBody();
            inValue.Body.id = id;
            return ((P29.Course.SOA.UnitTestProject.MyWebServiceTest.MyWebServiceSoap)(this)).GetNameByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetUserObjByIdResponse P29.Course.SOA.UnitTestProject.MyWebServiceTest.MyWebServiceSoap.GetUserObjById(P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetUserObjByIdRequest request) {
            return base.Channel.GetUserObjById(request);
        }
        
        public P29.Course.SOA.UnitTestProject.MyWebServiceTest.UserInfo GetUserObjById(int id) {
            P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetUserObjByIdRequest inValue = new P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetUserObjByIdRequest();
            inValue.Body = new P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetUserObjByIdRequestBody();
            inValue.Body.id = id;
            P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetUserObjByIdResponse retVal = ((P29.Course.SOA.UnitTestProject.MyWebServiceTest.MyWebServiceSoap)(this)).GetUserObjById(inValue);
            return retVal.Body.GetUserObjByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetUserObjByIdResponse> P29.Course.SOA.UnitTestProject.MyWebServiceTest.MyWebServiceSoap.GetUserObjByIdAsync(P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetUserObjByIdRequest request) {
            return base.Channel.GetUserObjByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetUserObjByIdResponse> GetUserObjByIdAsync(int id) {
            P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetUserObjByIdRequest inValue = new P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetUserObjByIdRequest();
            inValue.Body = new P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetUserObjByIdRequestBody();
            inValue.Body.id = id;
            return ((P29.Course.SOA.UnitTestProject.MyWebServiceTest.MyWebServiceSoap)(this)).GetUserObjByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetuserListResponse P29.Course.SOA.UnitTestProject.MyWebServiceTest.MyWebServiceSoap.GetuserList(P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetuserListRequest request) {
            return base.Channel.GetuserList(request);
        }
        
        public System.Collections.Generic.List<P29.Course.SOA.UnitTestProject.MyWebServiceTest.UserInfo> GetuserList() {
            P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetuserListRequest inValue = new P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetuserListRequest();
            inValue.Body = new P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetuserListRequestBody();
            P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetuserListResponse retVal = ((P29.Course.SOA.UnitTestProject.MyWebServiceTest.MyWebServiceSoap)(this)).GetuserList(inValue);
            return retVal.Body.GetuserListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetuserListResponse> P29.Course.SOA.UnitTestProject.MyWebServiceTest.MyWebServiceSoap.GetuserListAsync(P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetuserListRequest request) {
            return base.Channel.GetuserListAsync(request);
        }
        
        public System.Threading.Tasks.Task<P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetuserListResponse> GetuserListAsync() {
            P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetuserListRequest inValue = new P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetuserListRequest();
            inValue.Body = new P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetuserListRequestBody();
            return ((P29.Course.SOA.UnitTestProject.MyWebServiceTest.MyWebServiceSoap)(this)).GetuserListAsync(inValue);
        }
        
        public int Plus(int x, int y) {
            return base.Channel.Plus(x, y);
        }
        
        public System.Threading.Tasks.Task<int> PlusAsync(int x, int y) {
            return base.Channel.PlusAsync(x, y);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetJsonInfoResponse P29.Course.SOA.UnitTestProject.MyWebServiceTest.MyWebServiceSoap.GetJsonInfo(P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetJsonInfoRequest request) {
            return base.Channel.GetJsonInfo(request);
        }
        
        public string GetJsonInfo(int id, string name, int age) {
            P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetJsonInfoRequest inValue = new P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetJsonInfoRequest();
            inValue.Body = new P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetJsonInfoRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.age = age;
            P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetJsonInfoResponse retVal = ((P29.Course.SOA.UnitTestProject.MyWebServiceTest.MyWebServiceSoap)(this)).GetJsonInfo(inValue);
            return retVal.Body.GetJsonInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetJsonInfoResponse> P29.Course.SOA.UnitTestProject.MyWebServiceTest.MyWebServiceSoap.GetJsonInfoAsync(P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetJsonInfoRequest request) {
            return base.Channel.GetJsonInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetJsonInfoResponse> GetJsonInfoAsync(int id, string name, int age) {
            P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetJsonInfoRequest inValue = new P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetJsonInfoRequest();
            inValue.Body = new P29.Course.SOA.UnitTestProject.MyWebServiceTest.GetJsonInfoRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.age = age;
            return ((P29.Course.SOA.UnitTestProject.MyWebServiceTest.MyWebServiceSoap)(this)).GetJsonInfoAsync(inValue);
        }
    }
}
